name = "GenieTest"
uuid = "b272cc50-9a4f-43b1-8692-0510264c1fe6"
version = "0.1.0"
authors = ["Helmut HÃ¤nsel <helmut.haensel@gmx.de>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Electron = "a1bb12fb-d4d1-54b4-b10a-ee7951ef7ad3"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Stipple = "4acbeb90-81a0-11ea-1966-bdaff8155998"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
Electron = "6.1.1"
Test = "1.11.0"
TestItemRunner = "1.1.4"
