name = "GenieTest"
uuid = "b272cc50-9a4f-43b1-8692-0510264c1fe6"
authors = ["Helmut HÃ¤nsel <helmut.haensel@gmx.de>"]
version = "0.2.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Electron = "a1bb12fb-d4d1-54b4-b10a-ee7951ef7ad3"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Stipple = "4acbeb90-81a0-11ea-1966-bdaff8155998"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
Dates = "1.6"
Electron = "5, 6"
Genie = "5.35.3"
HTTP = "1"
Reexport = "1.2.2"
Stipple = "0.31.46"
StippleUI = "0.24.14"
Test = "1.6"
TestItemRunner = "1.1.4"
UUIDs = "1.6"
julia = "1.6"

[extras]
StippleUI = "a3c5d34a-b254-4859-a8fa-b86abb7e84a3"

[targets]
test = ["StippleUI"]
